# Generated by Django 4.2.24 on 2025-10-13 03:23

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(check=models.Q(('target_date__gt', django.db.models.functions.datetime.TruncDate(django.db.models.functions.datetime.Now()))), name='goal_target_date_in_future'),
        ),
    ]
