# Generated by Django 4.2.24 on 2025-10-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_name_goal_goal_target_date_in_future'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='saved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
