# Generated by Django 4.2.24 on 2025-09-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Eating Out', 'Eating Out'), ('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Health & Medical', 'Health & Medical'), ('Entertainment', 'Entertainment'), ('Savings & Investments', 'Savings & Investments'), ('Income', 'Income')], default='', max_length=100),
        ),
    ]
