# Generated by Django 4.2.24 on 2025-10-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_category_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', False)), fields=('owner', 'category'), name='uniq_category_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('category',), name='uniq_global_category_name'),
        ),
    ]
