# Generated by Django 4.2.24 on 2025-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_category_uniq_category_per_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Income'), ('OUT', 'Outgoing')], default='OUT', max_length=8),
        ),
    ]
