# Generated by Django 4.2.24 on 2025-10-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], default='OUT', max_length=8),
        ),
    ]
