# Generated by Django 4.2.24 on 2025-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('In', 'Income'), ('Out', 'Expense')], default='Out', max_length=8),
        ),
    ]
