# Generated by Django 4.2.24 on 2025-10-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
