# Generated by Django 4.2.24 on 2025-10-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurring',
        ),
    ]
