# Generated by Django 4.2.24 on 2025-09-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='period_start',
            field=models.DateField(),
        ),
    ]
