# Generated by Django 4.2.24 on 2025-10-12 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_remove_transaction_is_recurring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0002_alter_budget_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 'expense'}, on_delete=django.db.models.deletion.CASCADE, to='transactions.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period_start',
            field=models.DateField(help_text='First day of the month'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('owner', 'category', 'period_start')},
        ),
    ]
